linters:
  stylelint:
    config: 'stylelint.config.js'
files:
    ignore:        
        - 'assets/css/framework.css' 
        - 'assets/css/sass/framework.scss'
        - 'assets/css/sass/style.scss' 
fixers:
    enable: true